# Generated by Django 3.2 on 2021-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealcounts', '0003_alter_sheet_mealrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarikh',
            name='din',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
