# Generated by Django 3.2 on 2021-05-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealcounts', '0004_alter_tarikh_din'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='delta',
        ),
    ]
