# Generated by Django 3.2 on 2021-05-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealcounts', '0005_remove_member_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='khoroch',
        ),
    ]
