# Generated by Django 3.2 on 2021-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealcounts', '0007_member_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sheet',
        ),
        migrations.AlterField(
            model_name='member',
            name='joma',
            field=models.IntegerField(null=True),
        ),
    ]
